typedef enum {_taLeft, _taCenter, _taRight} TTextAlign;

typedef struct Screen TScreen;

typedef struct  Button_Round {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          *Caption;
  TTextAlign    TextAlign;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          Corner_Radius;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TButton_Round;

typedef struct  Label {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          *Caption;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Visible;
  char          Active;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TLabel;

typedef struct  CircleButton {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Radius;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          *Caption;
  TTextAlign     TextAlign;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCircleButton;

typedef struct  Line {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  First_Point_X;
  unsigned int  First_Point_Y;
  unsigned int  Second_Point_X;
  unsigned int  Second_Point_Y;
  char          Pen_Width;
  char          Visible;
  unsigned int  Color;
} TLine;

struct Screen {
  unsigned int           Color;
  unsigned int           Width;
  unsigned int           Height;
  unsigned int           ObjectsCount;
  unsigned int           Buttons_RoundCount;
  TButton_Round          * const code *Buttons_Round;
  unsigned int           LabelsCount;
  TLabel                 * const code *Labels;
  unsigned int           CircleButtonsCount;
  TCircleButton          * const code *CircleButtons;
  unsigned int           LinesCount;
  TLine                  * const code *Lines;
};

extern   TScreen                SelectSensor;
extern   TCircleButton          CircleButton1;
extern   TCircleButton          CircleButton2;
extern   TCircleButton          CircleButton3;
extern   TCircleButton          CircleButton4;
extern   TCircleButton          CircleButton5;
extern   TCircleButton          CircleButton6;
extern   TCircleButton          CircleButton7;
extern   TCircleButton          CircleButton8;
extern   TLabel                 Label2;
extern   TLine                  Line1;
extern   TLine                  Line2;
extern   TLabel                 * const code Screen1_Labels[1];
extern   TCircleButton          * const code Screen1_CircleButtons[8];
extern   TLine                  * const code Screen1_Lines[2];

extern   TScreen                RawAccel;
extern   TLabel                 Label3;
extern   TLabel                 X_Axis_Label;
extern   TLabel                 Y_Axis_Label;
extern   TLabel                 Z_Axis_Label;
extern   TLabel                 X_Axis_Data;
extern   TLabel                 Y_Axis_Data;
extern   TLabel                 Z_Axis_Data;
extern   TButton_Round          Back;
extern   TButton_Round          * const code Screen2_Buttons_Round[1];
extern   TLabel                 * const code Screen2_Labels[7];

extern   TScreen                RawGyro;
extern   TLabel                 Label1;
extern   TLabel                 Label4;
extern   TLabel                 Label5;
extern   TLabel                 Label6;
extern   TLabel                 Label7;
extern   TLabel                 Label8;
extern   TLabel                 Label9;
extern   TButton_Round          ButtonRound1;
extern   TButton_Round          * const code Screen3_Buttons_Round[1];
extern   TLabel                 * const code Screen3_Labels[7];

extern   TScreen                RawMagnet;
extern   TLabel                 Label10;
extern   TLabel                 Label11;
extern   TLabel                 Label12;
extern   TLabel                 Label13;
extern   TLabel                 Label14;
extern   TLabel                 Label15;
extern   TLabel                 Label16;
extern   TButton_Round          ButtonRound2;
extern   TButton_Round          * const code Screen4_Buttons_Round[1];
extern   TLabel                 * const code Screen4_Labels[7];

extern   TScreen                Accel;
extern   TLabel                 Label17;
extern   TLabel                 Label18;
extern   TLabel                 Label19;
extern   TLabel                 Label20;
extern   TLabel                 Label21;
extern   TLabel                 Label22;
extern   TLabel                 Label23;
extern   TButton_Round          ButtonRound3;
extern   TButton_Round          * const code Screen5_Buttons_Round[1];
extern   TLabel                 * const code Screen5_Labels[7];

extern   TScreen                Compass;
extern   TLabel                 Label24;
extern   TLabel                 Label25;
extern   TLabel                 Label28;
extern   TButton_Round          ButtonRound4;
extern   TButton_Round          * const code Screen6_Buttons_Round[1];
extern   TLabel                 * const code Screen6_Labels[3];

extern   TScreen                Gyro;
extern   TLabel                 Label31;
extern   TLabel                 Label32;
extern   TLabel                 Label33;
extern   TLabel                 Label34;
extern   TLabel                 Label35;
extern   TLabel                 Label36;
extern   TLabel                 Label37;
extern   TButton_Round          ButtonRound5;
extern   TButton_Round          * const code Screen7_Buttons_Round[1];
extern   TLabel                 * const code Screen7_Labels[7];

extern   TScreen                Inclinometer;
extern   TLabel                 Label38;
extern   TLabel                 Label39;
extern   TLabel                 Label40;
extern   TLabel                 Label41;
extern   TLabel                 Label42;
extern   TLabel                 Label43;
extern   TLabel                 Label44;
extern   TButton_Round          ButtonRound6;
extern   TButton_Round          * const code Screen8_Buttons_Round[1];
extern   TLabel                 * const code Screen8_Labels[7];

extern   TScreen                Orientation;
extern   TLabel                 Label45;
extern   TLabel                 Label46;
extern   TLabel                 Label47;
extern   TLabel                 Label48;
extern   TLabel                 Label49;
extern   TLabel                 Label50;
extern   TLabel                 Label51;
extern   TButton_Round          ButtonRound7;
extern   TLabel                 Label26;
extern   TLabel                 Label27;
extern   TButton_Round          * const code Screen9_Buttons_Round[1];
extern   TLabel                 * const code Screen9_Labels[9];


/////////////////////////
// Events Code Declarations
void BackOnClick();
void Button1OnClick();
void CircleButton1OnClick();
void CircleButton2OnClick();
void CircleButton3OnClick();
void CircleButton4OnClick();
void CircleButton5OnClick();
void CircleButton6OnClick();
void CircleButton7OnClick();
void CircleButton8OnClick();
/////////////////////////

/////////////////////////////////
// Caption variables Declarations
extern char CircleButton1_Caption[];
extern char CircleButton2_Caption[];
extern char CircleButton3_Caption[];
extern char CircleButton4_Caption[];
extern char CircleButton5_Caption[];
extern char CircleButton6_Caption[];
extern char CircleButton7_Caption[];
extern char CircleButton8_Caption[];
extern char Label2_Caption[];
extern char Line1_Caption[];
extern char Line2_Caption[];
extern char Label3_Caption[];
extern char X_Axis_Label_Caption[];
extern char Y_Axis_Label_Caption[];
extern char Z_Axis_Label_Caption[];
extern char X_Axis_Data_Caption[];
extern char Y_Axis_Data_Caption[];
extern char Z_Axis_Data_Caption[];
extern char Back_Caption[];
extern char Label1_Caption[];
extern char Label4_Caption[];
extern char Label5_Caption[];
extern char Label6_Caption[];
extern char Label7_Caption[];
extern char Label8_Caption[];
extern char Label9_Caption[];
extern char ButtonRound1_Caption[];
extern char Label10_Caption[];
extern char Label11_Caption[];
extern char Label12_Caption[];
extern char Label13_Caption[];
extern char Label14_Caption[];
extern char Label15_Caption[];
extern char Label16_Caption[];
extern char ButtonRound2_Caption[];
extern char Label17_Caption[];
extern char Label18_Caption[];
extern char Label19_Caption[];
extern char Label20_Caption[];
extern char Label21_Caption[];
extern char Label22_Caption[];
extern char Label23_Caption[];
extern char ButtonRound3_Caption[];
extern char Label24_Caption[];
extern char Label25_Caption[];
extern char Label28_Caption[];
extern char ButtonRound4_Caption[];
extern char Label31_Caption[];
extern char Label32_Caption[];
extern char Label33_Caption[];
extern char Label34_Caption[];
extern char Label35_Caption[];
extern char Label36_Caption[];
extern char Label37_Caption[];
extern char ButtonRound5_Caption[];
extern char Label38_Caption[];
extern char Label39_Caption[];
extern char Label40_Caption[];
extern char Label41_Caption[];
extern char Label42_Caption[];
extern char Label43_Caption[];
extern char Label44_Caption[];
extern char ButtonRound6_Caption[];
extern char Label45_Caption[];
extern char Label46_Caption[];
extern char Label47_Caption[];
extern char Label48_Caption[];
extern char Label49_Caption[];
extern char Label50_Caption[];
extern char Label51_Caption[];
extern char ButtonRound7_Caption[];
extern char Label26_Caption[];
extern char Label27_Caption[];
/////////////////////////////////

void DrawScreen(TScreen *aScreen);
void DrawRoundButton(TButton_Round *Around_button);
void DrawLabel(TLabel *ALabel);
void DrawCircleButton(TCircleButton *ACircle_button);
void DrawLine(TLine *Aline);
void Check_TP();
void Start_TP();
void Process_TP_Press(unsigned int X, unsigned int Y);
void Process_TP_Up(unsigned int X, unsigned int Y);
void Process_TP_Down(unsigned int X, unsigned int Y);
